use_frameworks!

platform :ios, '10.0'

target 'SFBluetooth_Example' do
  pod 'SFBluetooth', :path => '../'

  target 'SFBluetooth_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
